using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.IO;
using System.Linq;

namespace InlineArrayGenerator;

[Generator(LanguageNames.CSharp)]
internal sealed unsafe class InlineArraySourceGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider.ForAttributeWithMetadataName(
            GeneratorHelpers.AttributeMetadataName,
            (syntax, token) => syntax is StructDeclarationSyntax,
            (context, token) => {
                var count = (int)context.Attributes[0].ConstructorArguments[0].Value!;
                var type = (ITypeSymbol)context.TargetSymbol;

                var fields = type
                    .GetMembers()
                    .OfType<IFieldSymbol>()
                    .Where(field => !field.IsStatic);

                return new InlineArrayRecord(count, type, fields.Single().Type);
            });

        context.RegisterSourceOutput(provider, static (context, array) => {
            using var output = new StringWriter();
            using var writer = new IndentedTextWriter(output);

            writer.WriteLine($"#pragma warning disable");
            writer.WriteLine($"/// <auto-generated/>");
            writer.WriteLine();

            if (!string.IsNullOrEmpty(array.ArrayType.ContainingNamespace))
            {
                writer.WriteLine($"namespace {array.ArrayType.ContainingNamespace}");
                writer.WriteLine($"{{");
                writer.Indent++;
            }

            var typeNest = new List<TypeRecord>();

            for (var type = array.ArrayType; type != null; type = type.ContainingType)
            {
                typeNest.Insert(0, type);
            }

            foreach (var parent in typeNest)
            {
                writer.Write("partial ");

                if (parent.TypeKind == TypeKind.Class)
                {
                    writer.Write("class ");
                }
                else
                {
                    writer.Write("struct ");
                }

                writer.WriteLine(parent.Name);
                writer.WriteLine("{");
                writer.Indent++;
            }

            for (int i = 1; i < array.Length; i++)
            {
                writer.Write("private ");

                if (array.ElementType.TypeKind is TypeKind.Pointer or TypeKind.FunctionPointer)
                {
                    writer.Write("unsafe ");
                }

                writer.WriteLine($"{array.ElementType.FullyQualifiedName} __inline_{i};");
            }

            if (array.IsRefLike || array.ElementType.TypeKind is TypeKind.Pointer or TypeKind.FunctionPointer)
            {
                writer.WriteLine();
                writer.WriteLine($"[global::System.Diagnostics.CodeAnalysis.UnscopedRefAttribute]");
                writer.WriteLine($"public unsafe readonly ref {array.ElementType.FullyQualifiedName} this[int index]");
                writer.WriteLine("{");
                writer.Indent++;
                writer.WriteLine("get");
                writer.WriteLine("{");
                writer.Indent++;
                writer.WriteLine($"fixed ({array.ArrayType.Name}* pThis = &this)");
                writer.WriteLine("{");
                writer.Indent++;
                writer.WriteLine($"return ref (({array.ElementType.FullyQualifiedName}*)pThis)[index];");
                writer.Indent--;
                writer.WriteLine("}");
                writer.Indent--;
                writer.WriteLine("}");
                writer.Indent--;
                writer.WriteLine("}");
                writer.WriteLine();
                writer.WriteLine($"[global::System.Diagnostics.CodeAnalysis.UnscopedRefAttribute]");
                writer.WriteLine($"public unsafe readonly ref {array.ElementType.FullyQualifiedName} this[global::System.Index index]");
                writer.WriteLine("{");
                writer.Indent++;
                writer.WriteLine("get");
                writer.WriteLine("{");
                writer.Indent++;
                writer.WriteLine($"fixed ({array.ArrayType.Name}* pThis = &this)");
                writer.WriteLine("{");
                writer.Indent++;
                writer.WriteLine($"return ref (({array.ElementType.FullyQualifiedName}*)pThis)[index.GetOffset({array.Length})];");
                writer.Indent--;
                writer.WriteLine("}");
                writer.Indent--;
                writer.WriteLine("}");
                writer.Indent--;
                writer.WriteLine("}");
            }
            else
            {
                writer.WriteLine();
                writer.WriteLine($"[global::System.Diagnostics.CodeAnalysis.UnscopedRefAttribute]");
                writer.WriteLine($"public readonly ref {array.ElementType.FullyQualifiedName} this[int index] => ref ((global::System.Span<{array.ElementType.FullyQualifiedName}>)this)[index];");
                writer.WriteLine();
                writer.WriteLine($"[global::System.Diagnostics.CodeAnalysis.UnscopedRefAttribute]");
                writer.WriteLine($"public readonly ref {array.ElementType.FullyQualifiedName} this[global::System.Index index] => ref ((global::System.Span<{array.ElementType.FullyQualifiedName}>)this)[index];");
                writer.WriteLine();
                writer.WriteLine($"[global::System.Diagnostics.CodeAnalysis.UnscopedRefAttribute]");
                writer.WriteLine($"public readonly global::System.Span<{array.ElementType.FullyQualifiedName}> this[global::System.Range range] => ((global::System.Span<{array.ElementType.FullyQualifiedName}>)this)[range];");
                writer.WriteLine();
                writer.WriteLine($"public static implicit operator global::System.ReadOnlySpan<{array.ElementType.FullyQualifiedName}>(in {array.ArrayType.Name} array)");
                writer.WriteLine("{");
                writer.Indent++;
                writer.WriteLine($"ref var r0 = ref global::System.Runtime.CompilerServices.Unsafe.AsRef(in array);");
                writer.WriteLine($"ref var r1 = ref global::System.Runtime.CompilerServices.Unsafe.As<{array.ArrayType.Name}, {array.ElementType.FullyQualifiedName}>(ref r0);");
                writer.WriteLine($"return global::System.Runtime.InteropServices.MemoryMarshal.CreateReadOnlySpan(ref r1, {array.Length});");
                writer.Indent--;
                writer.WriteLine("}");
                writer.WriteLine();
                writer.WriteLine($"public static implicit operator global::System.Span<{array.ElementType.FullyQualifiedName}>(in {array.ArrayType.Name} array)");
                writer.WriteLine("{");
                writer.Indent++;
                writer.WriteLine($"ref var r0 = ref global::System.Runtime.CompilerServices.Unsafe.AsRef(in array);");
                writer.WriteLine($"ref var r1 = ref global::System.Runtime.CompilerServices.Unsafe.As<{array.ArrayType.Name}, {array.ElementType.FullyQualifiedName}>(ref r0);");
                writer.WriteLine($"return global::System.Runtime.InteropServices.MemoryMarshal.CreateSpan(ref r1, {array.Length});");
                writer.Indent--;
                writer.WriteLine("}");
            }

            foreach (var parent in typeNest)
            {
                writer.Indent--;
                writer.WriteLine("}");
            }

            if (!string.IsNullOrEmpty(array.ArrayType.ContainingNamespace))
            {
                writer.Indent--;
                writer.WriteLine($"}}");
            }

            context.AddSource($"{array.ArrayType.FullyQualifiedMetadataName}.g.cs", SourceText.From(output.ToString(), GeneratorHelpers.Utf8NoBom));
        });
    }
}
